CREATE TABLE customer (
    customer_id NUMERIC(3,0) PRIMARY KEY,
    customer_name VARCHAR(30) NOT NULL,
    CHECK (customer_id  BETWEEN 299 AND 1000)
);

CREATE TABLE category (
    category_id CHAR(1) PRIMARY KEY,
    category_name VARCHAR(20) NOT NULL
);

CREATE TABLE user_table (
    user_table_id NUMERIC(3,0) PRIMARY KEY,
    user_table_name VARCHAR(30) NOT NULL,
    CHECK (user_table_id  BETWEEN 99 AND 300)
);

CREATE TABLE valid_status_table (
    valid_status VARCHAR(10) PRIMARY KEY
);

CREATE TABLE ticket (
    ticket_id NUMERIC(4,0) PRIMARY KEY,
    category_id CHAR(1) REFERENCES category,
    user_ticket_id NUMERIC(3,0) REFERENCES user_table,
    customer_id NUMERIC(3,0) REFERENCES customer,
    curr_status VARCHAR(10) NOT NULL REFERENCES valid_status_table,
    comment VARCHAR(255)
);


CREATE TABLE Status_History (
    status_id INT GENERATED BY DEFAULT AS IDENTITY(
        START WITH 10000
        INCREMENT BY 1
        MAXVALUE 50000
    ) PRIMARY KEY,
    ticket_id NUMERIC(4,0) REFERENCES ticket,
    old_status VARCHAR(10),
    new_status VARCHAR(10) NOT NULL
);
    -- CHECK (status_id  BETWEEN 9999 AND 50001)

CREATE TABLE Assignment (
    assignment_id INT GENERATED BY DEFAULT AS IDENTITY(
        START WITH 50000
        INCREMENT BY 1
        MAXVALUE 99999
    ) PRIMARY KEY,
    ticket_id NUMERIC(4,0) REFERENCES ticket,
    old_user_id VARCHAR(10),
    new_user_id VARCHAR(10) NOT NULL,
    CHECK (assignment_id  BETWEEN 50000 AND 100000)
);

